language: python
python:
 - "3.6"
 - "3.7"
dist: bionic
env:
 - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
before_install:
 - sudo apt-get install -y python3-odb-api
install:
 - pip install -r requirements.txt
script:
 - pytest
