# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "deb http://us.archive.ubuntu.com/ubuntu bionic main" | sudo tee -a /etc/apt/sources.list
      - run: echo "deb http://us.archive.ubuntu.com/ubuntu bionic universe" | sudo tee -a /etc/apt/sources.list
      - run: sudo apt-get update
      - run: sudo apt-get install libodb-api-0d
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest-cov
            pip install pytest-flake8
            pip install coveralls

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest -s --flake8 --cov=py3odb
            coveralls

      - store_artifacts:
          path: test-reports
          destination: test-reports
