# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "deb http://deb.debian.org/debian buster main" | sudo tee -a /etc/apt/sources.list
      - run: echo "deb http://us.archive.ubuntu.com/ubuntu bionic universe" | sudo tee -a /etc/apt/sources.list
      - run: sudo apt-get update
      - run: sudo apt-get install libodb-api-0d
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest-cov
            pip install pytest-flake8
            pip install codecov

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --flake8 --cov=py3odb --cov-report html:htmlcov/unit.html tests/unit
            pytest --flake8 --cov=py3odb --cov-report html:htmlcov/integration.html tests/integration
            pytest --flake8 --cov=py3odb
            codecov 

      - store_artifacts:
          path: htmlcov
          destination: test-reports
